# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 13, 26, 26, 817140), verbose_name='添加时间'),
        ),
    ]
